# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSmokeTest:

    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.driver.set_window_size(1920, 1080)

    def teardown_method(self, method):
        self.driver.quit()

    def test_homePage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")

        assert self.driver.title == "Teton Idaho CoC"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title h1").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-logo img").is_displayed()
        nav_text = self.driver.find_element(By.TAG_NAME, "nav").text
        assert "Home" in nav_text
        assert "Join" in nav_text
        assert "Directory" in nav_text
        assert "Admin" in nav_text
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 img").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 img").is_displayed()

    def test_joinPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        join_link = self.driver.find_element(By.LINK_TEXT, "Join")
        assert join_link.is_displayed()
        self.driver.execute_script("arguments[0].scrollIntoView(true);", join_link)
        join_link.click()
        assert self.driver.find_element(By.NAME, "fname").is_displayed()
        self.driver.find_element(By.NAME, "fname").send_keys("Test")
        self.driver.find_element(By.NAME, "lname").send_keys("User")
        self.driver.find_element(By.NAME, "bizname").send_keys("Test Biz")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Owner")
        submit = self.driver.find_element(By.NAME, "submit")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", submit)
        submit.click()
        assert self.driver.find_element(By.NAME, "email").is_displayed()

    def test_directoryPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
        self.driver.find_element(By.ID, "directory-grid").click()
        assert "Teton Turf and Tree" in self.driver.find_element(By.TAG_NAME, "body").text
        self.driver.find_element(By.ID, "directory-list").click()
        assert "Teton Turf and Tree" in self.driver.find_element(By.TAG_NAME, "body").text

    def test_adminPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
        self.driver.find_element(By.ID, "username").send_keys("wronguser")
        self.driver.find_element(By.ID, "password").send_keys("wrongpass")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit").click()
        error = self.driver.find_element(By.CLASS_NAME, "errorMessage").text
        assert "Invalid username and password" in error