# Generated by Selenium IDE - IDE-style Python/pytest version
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestSmokeTest:
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        options.add_argument("--disable-gpu")
        options.add_argument("--window-size=1920,1080")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_homePage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(1920, 1080)
        nav = self.wait.until(EC.visibility_of_element_located((By.TAG_NAME, "nav")))
        assert "Home" in nav.text
        assert "Join" in nav.text
        assert "Directory" in nav.text
        assert "Admin" in nav.text
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title h1").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-logo img").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 img").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 img").is_displayed()
        assert self.driver.title == "Teton Idaho CoC"

    def test_joinPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(1920, 1080)
        join_link = self.wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Join")))
        self.driver.execute_script("arguments[0].scrollIntoView(true);", join_link)
        ActionChains(self.driver).move_to_element(join_link).click().perform()
        fname = self.wait.until(EC.visibility_of_element_located((By.NAME, "fname")))
        fname.send_keys("Test")
        self.driver.find_element(By.NAME, "lname").send_keys("User")
        self.driver.find_element(By.NAME, "bizname").send_keys("Test Biz")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Owner")
        submit = self.driver.find_element(By.NAME, "submit")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", submit)
        ActionChains(self.driver).move_to_element(submit).click().perform()
        email_field = self.wait.until(EC.visibility_of_element_located((By.NAME, "email")))
        assert email_field.is_displayed()

    def test_directoryPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
        self.driver.set_window_size(1920, 1080)
        grid_btn = self.wait.until(EC.element_to_be_clickable((By.ID, "directory-grid")))
        self.driver.execute_script("arguments[0].scrollIntoView(true);", grid_btn)
        ActionChains(self.driver).move_to_element(grid_btn).click().perform()
        assert "Teton Turf and Tree" in self.driver.find_element(By.TAG_NAME, "body").text
        list_btn = self.wait.until(EC.element_to_be_clickable((By.ID, "directory-list")))
        self.driver.execute_script("arguments[0].scrollIntoView(true);", list_btn)
        ActionChains(self.driver).move_to_element(list_btn).click().perform()
        assert "Teton Turf and Tree" in self.driver.find_element(By.TAG_NAME, "body").text

    def test_adminPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
        self.driver.set_window_size(1920, 1080)
        username = self.wait.until(EC.visibility_of_element_located((By.ID, "username")))
        username.send_keys("wronguser")
        self.driver.find_element(By.ID, "password").send_keys("wrongpass")
        submit = self.driver.find_element(By.CSS_SELECTOR, ".mysubmit")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", submit)
        ActionChains(self.driver).move_to_element(submit).click().perform()
        error = self.wait.until(EC.visibility_of_element_located((By.CLASS_NAME, "errorMessage")))
        assert "Invalid username and password" in error.text
